In [ ]:
import pandas as pd

file_path = '/content/drive/MyDrive/Colab Notebooks/Thesis/Data/Mechanisms Data /(finances) cps_00006.csv'
# Load into a specific dataframe to avoid overlap
df_acs = pd.read_csv(file_path)

# Task
Perform data preparation and filtering on the dataset loaded from "/content/drive/MyDrive/Colab Notebooks/Thesis/Data/Mechanisms Data /(finances) cps_00006.csv". Specifically: inspect the dataframe's structure (shape, types, years); verify the existence of key columns (YEAR, SERIAL, PERNUM, ASECWT, etc.); calculate a `birth_year` column and filter for birth cohorts 1981-1984; verify cohort coverage by year; filter for childhood observations (AGE <= 18); analyze household structure via the `RELATE` column; remove records where `STATEFIP` > 56; and save the final cleaned dataframe as `df_children`.

## Load and Inspect Data

### Subtask:
Inspect the already loaded dataframe structure (shape, types, years).

**Reasoning**:
Inspect the already loaded dataframe `df_acs` to understand its structure, columns, data types, and the temporal coverage of the data.

In [ ]:
print("Shape of the dataframe:")
print(df_acs.shape)
print("\nColumn names:")
print(df_acs.columns)
print("\nData types:")
print(df_acs.dtypes)

print("\nYear range:")
print(f"Min Year: {df_acs['YEAR'].min()}")
print(f"Max Year: {df_acs['YEAR'].max()}")

Shape of the dataframe:
(3896289, 34)

Column names:
Index(['YEAR', 'SERIAL', 'MONTH', 'CPSID', 'ASECFLAG', 'ASECWTH', 'STATEFIP',
       'HHINCOME', 'FOODSTMP', 'STAMPVAL', 'PERNUM', 'CPSIDP', 'CPSIDV',
       'ASECWT', 'RELATE', 'AGE', 'SEX', 'RACE', 'MOMLOC', 'POPLOC', 'FAMSIZE',
       'NCHILD', 'YNGCH', 'BPL', 'HISPAN', 'EMPSTAT', 'CLASSWKR', 'WKSWORK1',
       'UHRSWORKLY', 'INCWELFR', 'SRCWELFR', 'OFFPOV', 'HIMCAIDLY',
       'HCOVPRIV'],
      dtype='object')

Data types:
YEAR            int64
SERIAL          int64
MONTH           int64
CPSID           int64
ASECFLAG        int64
ASECWTH       float64
STATEFIP        int64
HHINCOME        int64
FOODSTMP        int64
STAMPVAL        int64
PERNUM          int64
CPSIDP          int64
CPSIDV          int64
ASECWT        float64
RELATE          int64
AGE             int64
SEX             int64
RACE            int64
MOMLOC          int64
POPLOC          int64
FAMSIZE         int64
NCHILD          int64
YNGCH           int64
BPL           float64
HISPAN          int64
EMPSTAT         int64
CLASSWKR        int64
WKSWORK1        int64
UHRSWORKLY      int64
INCWELFR        int64
SRCWELFR        int64
OFFPOV          int64
HIMCAIDLY       int64
HCOVPRIV      float64
dtype: object

Year range:
Min Year: 1981
Max Year: 2004

In [ ]:
# --- Step 1: Detailed Exploration and Column Check ---

# List of columns to check
check_cols = [
    'YEAR', 'SERIAL', 'PERNUM', 'ASECWT', 'AGE', 'SEX', 'RACE', 'HISPAN', 'STATEFIP',
    'RELATE', 'MOMLOC', 'POPLOC', 'FAMSIZE', 'NCHILD', 'HHINCOME', 'OFFPOV', 'FOODSTMP',
    'STAMPVAL', 'INCWELFR', 'HIMCAIDLY', 'HCOVPRIV', 'PHINSUR', 'COVERGH',
    'EMPSTAT', 'WKSWORK1', 'UHRSWORKLY', 'INCWAGE', 'CLASSWKR'
]
# Note: Adjusted some variable names to match what I saw in df_acs.columns earlier
# (e.g., INCWELFR vs INCWELF, UHRSWORKLY vs UHRSWORK)

missing_cols = [c for c in check_cols if c not in df_acs.columns]
if missing_cols:
    print(f"WARNING: The following columns are MISSING: {missing_cols}")
else:
    print("SUCCESS: All key columns are present.")

print("\n--- Descriptive Stats for AGE ---")
print(df_acs['AGE'].describe())

print("\n--- Value Counts for RELATE (Top 20) ---")
print(df_acs['RELATE'].value_counts().sort_index().head(20))

print("\n--- Value Counts for MOMLOC (Top 10) ---")
print(df_acs['MOMLOC'].value_counts().sort_index().head(10))

print("\n--- Value Counts for POPLOC (Top 10) ---")
print(df_acs['POPLOC'].value_counts().sort_index().head(10))

WARNING: The following columns are MISSING: ['PHINSUR', 'COVERGH', 'INCWAGE']

--- Descriptive Stats for AGE ---
count    3.896289e+06
mean     3.389481e+01
std      2.200820e+01
min      0.000000e+00
25%      1.500000e+01
50%      3.200000e+01
75%      4.900000e+01
max      9.900000e+01
Name: AGE, dtype: float64

--- Value Counts for RELATE (Top 20) ---
RELATE
101     1448388
201      815597
301     1298962
303       10372
501       22360
701       23876
901       44534
1001      92285
1113      18951
1114      23516
1115      22418
1241       4766
1242       2826
1260      67438
Name: count, dtype: int64

--- Value Counts for MOMLOC (Top 10) ---
MOMLOC
0    2546325
1     425274
2     864037
3      25292
4      16322
5       9357
6       4954
7       2329
8       1140
9        550
Name: count, dtype: int64

--- Value Counts for POPLOC (Top 10) ---
POPLOC
0    2816994
1     888476
2     158969
3      11574
4       9020
5       5503
6       2880
7       1379
8        702
9        330
Name: count, dtype: int64

In [ ]:
# --- Step 2: Create birth_year and Initial Filter ---

# 1. Create birth_year
df_acs['birth_year'] = df_acs['YEAR'] - df_acs['AGE']

# 2. Print distribution
print("\n--- Birth Year Distribution (Sample) ---")
print(df_acs['birth_year'].value_counts().sort_index().loc[1975:1990])

# 3. Filter for 1981-1984 cohorts
target_cohorts = [1981, 1982, 1983, 1984]
df_cohorts = df_acs[df_acs['birth_year'].isin(target_cohorts)].copy()

print(f"\nOriginal Shape: {df_acs.shape}")
print(f"Shape after Cohort Filter (1981-1984): {df_cohorts.shape}")

--- Birth Year Distribution (Sample) ---
birth_year
1975    51537
1976    51383
1977    51989
1978    53502
1979    53696
1980    56192
1981    58115
1982    54760
1983    54128
1984    51503
1985    50620
1986    49657
1987    47318
1988    45397
1989    43161
1990    42233
Name: count, dtype: int64

Original Shape: (3896289, 35)
Shape after Cohort Filter (1981-1984): (218506, 35)

In [ ]:
# --- Step 3: Identify Children using Multiple Criteria ---

# Criterion A: Age <= 18
df_cohorts['is_child_age'] = (df_cohorts['AGE'] <= 18).astype(int)

# Criterion B: Relationship (301=Child, 303=Stepchild)
# Adjust codes if RELATE inspection shows different standard (e.g. 301 vs 3)
df_cohorts['is_child_relate'] = df_cohorts['RELATE'].isin([301, 303, 1114]).astype(int) # Added 1114 (Grandchild) just in case, but primary is 301/303

# Criterion C: Parent Pointer
df_cohorts['is_child_parent_ptr'] = ((df_cohorts['MOMLOC'] > 0) | (df_cohorts['POPLOC'] > 0)).astype(int)

# Cross-tabs
print("\n--- Cross-tab: Age <= 18 vs. Relate --- ভা")
print(pd.crosstab(df_cohorts['is_child_age'], df_cohorts['is_child_relate']))

print("\n--- Cross-tab: Age <= 18 vs. Parent Pointer ---")
print(pd.crosstab(df_cohorts['is_child_age'], df_cohorts['is_child_parent_ptr']))

# Final Child Indicator: Age <= 18 AND Parent Present
df_cohorts['is_child'] = ((df_cohorts['is_child_age'] == 1) & (df_cohorts['is_child_parent_ptr'] == 1)).astype(int)

print("\n--- Final Child Indicator Counts ---")
print(df_cohorts['is_child'].value_counts())

print("\n--- Age Distribution of Identified Children ---")
print(df_cohorts[df_cohorts['is_child'] == 1]['AGE'].value_counts().sort_index())

# Filter to keep only identified children
df_children = df_cohorts[df_cohorts['is_child'] == 1].copy()
print(f"\nFinal Shape (df_children): {df_children.shape}")

--- Cross-tab: Age <= 18 vs. Relate --- ভা
is_child_relate      0       1
is_child_age
0                14385   21247
1                16899  165975

--- Cross-tab: Age <= 18 vs. Parent Pointer ---
is_child_parent_ptr      0       1
is_child_age
0                    13648   21984
1                     5680  177194

--- Final Child Indicator Counts ---
is_child
1    177194
0     41312
Name: count, dtype: int64

--- Age Distribution of Identified Children ---
AGE
0     10544
1     10307
2     10324
3     10390
4      9958
5      9747
6      9599
7      9718
8      9583
9      9560
10     9502
11     9299
12     8796
13     8488
14     8053
15     7676
16     7534
17     9067
18     9049
Name: count, dtype: int64

Final Shape (df_children): (177194, 39)

In [ ]:
# --- Step 4: Validate the Child Sample ---

# 1. Cohort x Year Coverage
print("\n--- Cohort Coverage (Birth Year x Survey Year) ---")
# We expect a diagonal pattern where age increases with year for each cohort
crosstab_coverage = pd.crosstab(df_children['birth_year'], df_children['YEAR'])
display(crosstab_coverage)

# 2. Age at Survey Stats
df_children['age_at_survey'] = df_children['AGE']
print("\n--- Age at Survey Stats ---")
print(df_children['age_at_survey'].describe())

# 3. Obs per Birth Year
print("\n--- Observations per Birth Year ---")
print(df_children['birth_year'].value_counts().sort_index())

# 4. State Coverage
print("\n--- Observations per State (Top 5 & Bottom 5) ---")
state_counts = df_children['STATEFIP'].value_counts()
print("Top 5 States by Count:")
print(state_counts.head(5))
print("\nBottom 5 States by Count:")
print(state_counts.tail(5))

# Check for states with very low observations
low_obs_states = state_counts[state_counts < 50]
if not low_obs_states.empty:
    print(f"\nWARNING: The following states have < 50 observations: {low_obs_states.index.tolist()}")
else:
    print("\nSUCCESS: All states have >= 50 observations.")

# 5. Observations per Year
print("\n--- Observations per Survey Year ---")
print(df_children['YEAR'].value_counts().sort_index())

# 6. Filter Non-State Geographies (STATEFIP > 56)
# (Codes > 56 are usually territories or errors in this context)
n_before_state = len(df_children)
df_children = df_children[df_children['STATEFIP'] <= 56].copy()
n_dropped_state = n_before_state - len(df_children)

print(f"\nDropped {n_dropped_state} observations with STATEFIP > 56.")
print(f"Final Shape after Step 4: {df_children.shape}")

--- Cohort Coverage (Birth Year x Survey Year) ---

YEAR,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,...,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002
birth_year,,,,,,,,,,,,,,,,,,,,,
1981,2896,2624,2715,2749,2595,2529,2486,2443,2250,2434,...,2332,2330,2216,1943,1924,1851,1617,0,0,0
1982,0,2576,2548,2546,2632,2460,2411,2415,2271,2419,...,2359,2244,2223,1989,1938,1888,1844,1578,0,0
1983,0,0,2518,2582,2598,2596,2481,2525,2310,2530,...,2350,2258,2281,2041,2027,1955,1863,1825,2923,0
1984,0,0,0,2554,2553,2465,2413,2422,2282,2388,...,2281,2302,2299,1939,1894,1821,1840,1859,3547,2931

--- Age at Survey Stats ---
count    177194.000000
mean          8.565008
std           5.480219
min           0.000000
25%           4.000000
50%           8.000000
75%          13.000000
max          18.000000
Name: age_at_survey, dtype: float64

--- Observations per Birth Year ---
birth_year
1981    44824
1982    43114
1983    44648
1984    44608
Name: count, dtype: int64

--- Observations per State (Top 5 & Bottom 5) ---
Top 5 States by Count:
STATEFIP
6     17051
36    11047
48    11019
17     7328
12     6985
Name: count, dtype: int64

Bottom 5 States by Count:
STATEFIP
50    1557
9     1539
33    1474
44    1341
11    1143
Name: count, dtype: int64

SUCCESS: All states have >= 50 observations.

--- Observations per Survey Year ---
YEAR
1981     2896
1982     5200
1983     7781
1984    10431
1985    10378
1986    10050
1987     9791
1988     9805
1989     9113
1990     9771
1991     9981
1992     9485
1993     9322
1994     9134
1995     9019
1996     7912
1997     7783
1998     7515
1999     7164
2000     5262
2001     6470
2002     2931
Name: count, dtype: int64

Dropped 0 observations with STATEFIP > 56.
Final Shape after Step 4: (177194, 40)

In [ ]:
# --- Step 5: Link Parent Characteristics ---

# define columns to link
# Note: INCWAGE was missing in initial check. Using UHRSWORKLY instead of UHRSWORK.
parent_cols = ['YEAR', 'SERIAL', 'PERNUM', 'EMPSTAT', 'WKSWORK1', 'UHRSWORKLY', 'CLASSWKR']

# Create lookup table from ORIGINAL df_acs (before filtering)
# We need to ensure we don't have duplicates on keys, though CPS structure usually guarantees this per year/serial/pernum
parent_lookup = df_acs[parent_cols].copy()

# 1. Merge Mother's Characteristics
# Join on YEAR, SERIAL, and MOMLOC (Child) == PERNUM (Parent)
df_children = df_children.merge(
    parent_lookup,
    left_on=['YEAR', 'SERIAL', 'MOMLOC'],
    right_on=['YEAR', 'SERIAL', 'PERNUM'],
    how='left',
    suffixes=('', '_mom')
)

# Rename the newly added columns
rename_mom = {
    'EMPSTAT': 'mom_EMPSTAT',
    'WKSWORK1': 'mom_WKSWORK1',
    'UHRSWORKLY': 'mom_UHRSWORKLY',
    'CLASSWKR': 'mom_CLASSWKR',
    'PERNUM': 'mom_PERNUM_check' # Just for verification, can drop later
}
df_children.rename(columns=rename_mom, inplace=True)

# 2. Merge Father's Characteristics
# Join on YEAR, SERIAL, and POPLOC (Child) == PERNUM (Parent)
df_children = df_children.merge(
    parent_lookup,
    left_on=['YEAR', 'SERIAL', 'POPLOC'],
    right_on=['YEAR', 'SERIAL', 'PERNUM'],
    how='left',
    suffixes=('', '_dad')
)

# Rename the newly added columns (merges usually add suffixes to collisions, but here we control it)
# Since 'EMPSTAT' etc were renamed in the previous step, the new ones coming in might have no suffix or '_dad' depending on overlap.
# Let's handle the specific naming resulting from the merge.

# The merge above likely created columns like 'EMPSTAT', 'WKSWORK1' again because the left side keys were consumed.
# Let's manually rename the columns that were just added.
rename_dad = {
    'EMPSTAT': 'dad_EMPSTAT',
    'WKSWORK1': 'dad_WKSWORK1',
    'UHRSWORKLY': 'dad_UHRSWORKLY',
    'CLASSWKR': 'dad_CLASSWKR',
    'PERNUM': 'dad_PERNUM_check'
}
df_children.rename(columns=rename_dad, inplace=True)

# 3. Check Merge Success
print("\n--- Parent Merge Success Rates ---")
n_total = len(df_children)
n_mom = df_children['mom_EMPSTAT'].notna().sum()
n_dad = df_children['dad_EMPSTAT'].notna().sum()
n_both = ((df_children['mom_EMPSTAT'].notna()) & (df_children['dad_EMPSTAT'].notna())).sum()
n_neither = ((df_children['mom_EMPSTAT'].isna()) & (df_children['dad_EMPSTAT'].isna())).sum()

print(f"Total Children: {n_total}")
print(f"Linked to Mother: {n_mom} ({n_mom/n_total:.1%})")
print(f"Linked to Father: {n_dad} ({n_dad/n_total:.1%})")
print(f"Linked to BOTH:   {n_both} ({n_both/n_total:.1%})")
print(f"Linked to NEITHER:{n_neither} ({n_neither/n_total:.1%})")

# Check for rows where we expected a link (MOMLOC>0) but didn't get one
missing_mom_link = df_children[(df_children['MOMLOC'] > 0) & (df_children['mom_EMPSTAT'].isna())]
if len(missing_mom_link) > 0:
    print(f"\nWARNING: {len(missing_mom_link)} rows have MOMLOC > 0 but failed to link mother data.")
    print("Example failing rows:")
    display(missing_mom_link[['YEAR', 'SERIAL', 'PERNUM', 'MOMLOC', 'POPLOC']].head())
else:
    print("\nSUCCESS: All MOMLOC pointers successfully linked.")

--- Parent Merge Success Rates ---
Total Children: 177194
Linked to Mother: 177194 (100.0%)
Linked to Father: 139333 (78.6%)
Linked to BOTH:   139333 (78.6%)
Linked to NEITHER:0 (0.0%)

SUCCESS: All MOMLOC pointers successfully linked.

In [ ]:
# --- Step 6: Household Structure Indicators ---

# 1. Construct Indicators
# single_parent: 1 if exactly one parent is present (MOMLOC>0 xor POPLOC>0)
# We already know at least one is present from Step 3.
df_children['single_parent'] = (
    ((df_children['MOMLOC'] > 0) & (df_children['POPLOC'] == 0)) |
    ((df_children['MOMLOC'] == 0) & (df_children['POPLOC'] > 0))
).astype(int)

df_children['num_parents'] = (df_children['MOMLOC'] > 0).astype(int) + (df_children['POPLOC'] > 0).astype(int)

# 2. Structure Statistics
print("\n--- Household Structure Stats ---")
print(f"Single Parent Rate: {df_children['single_parent'].mean():.2%}")
print("\nNumber of Parents in Household (Value Counts):")
print(df_children['num_parents'].value_counts().sort_index())

print("\n--- Single Parent Rate by Birth Year ---")
print(df_children.groupby('birth_year')['single_parent'].mean())

print("\n--- Single Parent Rate by Survey Year ---")
# Printing full series to see trends over time
print(df_children.groupby('YEAR')['single_parent'].mean())

--- Household Structure Stats ---
Single Parent Rate: 24.52%

Number of Parents in Household (Value Counts):
num_parents
1     43449
2    133745
Name: count, dtype: int64

--- Single Parent Rate by Birth Year ---
birth_year
1981    0.240808
1982    0.245674
1983    0.245812
1984    0.248565
Name: single_parent, dtype: float64

--- Single Parent Rate by Survey Year ---
YEAR
1981    0.172307
1982    0.197500
1983    0.203059
1984    0.202090
1985    0.218636
1986    0.228259
1987    0.238484
1988    0.240388
1989    0.242950
1990    0.244499
1991    0.254884
1992    0.269373
1993    0.266252
1994    0.273593
1995    0.259009
1996    0.261754
1997    0.264037
1998    0.276780
1999    0.271496
2000    0.262638
2001    0.257960
2002    0.258956
Name: single_parent, dtype: float64

In [ ]:
# --- Step 7: Final Summary and Save ---

print("\n============================================")
print("       FINAL CHILD SAMPLE SUMMARY")
print("============================================")
print(f"Total Observations: {len(df_children)}")
print(f"Unique Children (based on YEAR+SERIAL+PERNUM): {len(df_children)}")
print(f"Unique Households (based on YEAR+SERIAL): {df_children[['YEAR', 'SERIAL']].drop_duplicates().shape[0]}")

print("\n--- Demographics ---")
print("Observations per Birth Year:")
print(df_children['birth_year'].value_counts().sort_index())

print("\nAge Distribution:")
print(df_children['AGE'].value_counts().sort_index())

print("\n--- Geographic Coverage ---")
print(f"Number of Unique States: {df_children['STATEFIP'].nunique()}")
print("Top 10 States by Observations:")
print(df_children['STATEFIP'].value_counts().head(10))
print("Bottom 10 States by Observations:")
print(df_children['STATEFIP'].value_counts().tail(10))

print(f"\nNumber of Unique Survey Years: {df_children['YEAR'].nunique()}")

print("\n--- Financial Conditions (Means) ---")
# Check if columns exist before printing
fin_cols = ['HHINCOME', 'OFFPOV', 'FOODSTMP', 'single_parent']
existing_fin_cols = [c for c in fin_cols if c in df_children.columns]
print(df_children[existing_fin_cols].mean())

print("\n--- Parent Employment (Means of Linked Parents) ---")
# mom_EMPSTAT: 10-12=Employed, 20-22=Unemployed, 30+=Not in Labor Force (checking if < 20 for 'Employed')
if 'mom_EMPSTAT' in df_children.columns:
    print(f"Mom Employment Rate (EMPSTAT < 20): {(df_children['mom_EMPSTAT'] < 20).mean():.2%}")
if 'dad_EMPSTAT' in df_children.columns:
    print(f"Dad Employment Rate (EMPSTAT < 20): {(df_children['dad_EMPSTAT'] < 20).mean():.2%}")

# Save
output_filename = 'df_children.csv'
df_children.to_csv(output_filename, index=False)
print(f"\nSUCCESS: Final dataframe saved to {output_filename}")
print(f"Final Shape: {df_children.shape}")

============================================
       FINAL CHILD SAMPLE SUMMARY
============================================
Total Observations: 177194
Unique Children (based on YEAR+SERIAL+PERNUM): 177194
Unique Households (based on YEAR+SERIAL): 148721

--- Demographics ---
Observations per Birth Year:
birth_year
1981    44824
1982    43114
1983    44648
1984    44608
Name: count, dtype: int64

Age Distribution:
AGE
0     10544
1     10307
2     10324
3     10390
4      9958
5      9747
6      9599
7      9718
8      9583
9      9560
10     9502
11     9299
12     8796
13     8488
14     8053
15     7676
16     7534
17     9067
18     9049
Name: count, dtype: int64

--- Geographic Coverage ---
Number of Unique States: 51
Top 10 States by Observations:
STATEFIP
6     17051
36    11047
48    11019
17     7328
12     6985
39     6867
42     6630
26     6496
34     5385
25     4728
Name: count, dtype: int64
Bottom 10 States by Observations:
STATEFIP
41    1889
15    1805
24    1801
23    1637
10    1615
50    1557
9     1539
33    1474
44    1341
11    1143
Name: count, dtype: int64

Number of Unique Survey Years: 22

--- Financial Conditions (Means) ---
HHINCOME         40510.817816
OFFPOV               1.888941
FOODSTMP             1.157246
single_parent        0.245206
dtype: float64

--- Parent Employment (Means of Linked Parents) ---
Mom Employment Rate (EMPSTAT < 20): 87.12%
Dad Employment Rate (EMPSTAT < 20): 70.55%

SUCCESS: Final dataframe saved to df_children.csv
Final Shape: (177194, 52)

# Task
To proceed, please provide the exact filename or path for the external data containing Medicaid eligibility and economic control variables.

## Identify External Data File

### Subtask:
Provide the exact filename or path for the external data containing Medicaid eligibility and economic control variables.

The external data file identified for Medicaid eligibility and economic control variables is: `/content/drive/MyDrive/Colab Notebooks/Thesis/Data/[Final]_US_Crime_Rates_1999_2010.csv`.

## Load External Data

### Subtask:
Load the specified external data file into a new DataFrame.

**Reasoning**:
Load the specified external CSV file into a new DataFrame named `df_external` and display its first 5 rows to inspect the data.

In [ ]:
file_path_external = '/content/drive/MyDrive/Colab Notebooks/Thesis/Data/[Final]_US_Crime_Rates_1999_2010.csv'
df_external = pd.read_csv(file_path_external)
print("First 5 rows of df_external:")
print(df_external.head())

First 5 rows of df_external:
   fips  year  age  crime_count  brthyr  Age State  Population   Drug_Rate  \
0     1  2000   19         1594    1981   19    AL       67769  142.395491
1     1  2001   19         1741    1982   19    AL       65031  141.009672
2     1  2001   20         1686    1981   20    AL       68511  133.263272
3     1  2002   19         1758    1983   19    AL       64169  154.124266
4     1  2002   20         1655    1982   20    AL       65515  152.636801

   Financial_Rate  ...  cumulative_eligibility  elig_0_5  elig_6_11  \
0       57.400877  ...                3.228658  1.000340   0.858396
1       66.122311  ...                3.559218  0.963729   0.939953
2       87.285253  ...                3.228658  1.000340   0.858396
3       55.946018  ...                3.929335  0.927237   0.999889
4       69.449744  ...                3.559218  0.963729   0.939953

   elig_12_18  trend_cohort  Childhood_Avg_Unemployment  \
0    1.369921             0                    7.957895
1    1.655536             1                    7.642105
2    1.369921             0                    7.957895
3    2.002209             2                    7.168421
4    1.655536             1                    7.642105

   economically_motivated_crimes  state_abb  childhood_avg_income  log(income)
0                     235.210790         AL                 10537     9.262648
1                     267.718473         AL                 10732     9.280985
2                     246.091868         AL                 10537     9.262648
3                     273.964064         AL                 10937     9.299907
4                     252.613905         AL                 10732     9.280985

[5 rows x 23 columns]

**Reasoning**:
Now that the external data is loaded, I need to inspect its structure, data types, and check for relevant columns to ensure it can be effectively merged with `df_children`.

In [ ]:
print("Shape of df_external:")
print(df_external.shape)

print("\nColumns of df_external:")
print(df_external.columns.tolist())

print("\nData types of df_external:")
print(df_external.dtypes)

print("\nDescriptive statistics for df_external (numeric columns):")
print(df_external.describe())

Shape of df_external:
(1198, 23)

Columns of df_external:
['fips', 'year', 'age', 'crime_count', 'brthyr', 'Age', 'State', 'Population', 'Drug_Rate', 'Financial_Rate', 'Property_Rate', 'PublicOrder_Rate', 'Violent_Rate', 'cumulative_eligibility', 'elig_0_5', 'elig_6_11', 'elig_12_18', 'trend_cohort', 'Childhood_Avg_Unemployment', 'economically_motivated_crimes', 'state_abb', 'childhood_avg_income', 'log(income)']

Data types of df_external:
fips                               int64
year                               int64
age                                int64
crime_count                        int64
brthyr                             int64
Age                                int64
State                             object
Population                         int64
Drug_Rate                        float64
Financial_Rate                   float64
Property_Rate                    float64
PublicOrder_Rate                 float64
Violent_Rate                     float64
cumulative_eligibility           float64
elig_0_5                         float64
elig_6_11                        float64
elig_12_18                       float64
trend_cohort                       int64
Childhood_Avg_Unemployment       float64
economically_motivated_crimes    float64
state_abb                         object
childhood_avg_income               int64
log(income)                      float64
dtype: object

Descriptive statistics for df_external (numeric columns):
              fips         year          age   crime_count       brthyr  \
count  1198.000000  1198.000000  1198.000000   1198.000000  1198.000000
mean     29.293823  2004.006678    21.504174   1428.787145  1982.502504
std      15.639436     2.037236     1.706903   1757.957406     1.117751
min       1.000000  2000.000000    19.000000      1.000000  1981.000000
25%      17.000000  2003.000000    20.000000    344.250000  1982.000000
50%      29.500000  2004.000000    22.000000    964.500000  1983.000000
75%      42.000000  2005.750000    23.000000   1795.500000  1983.750000
max      56.000000  2008.000000    24.000000  12861.000000  1984.000000

               Age     Population    Drug_Rate  Financial_Rate  Property_Rate  \
count  1198.000000    1198.000000  1198.000000     1198.000000    1198.000000
mean     21.504174   78865.989149   156.762153       40.562113     154.607350
std       1.706903   90548.310102    72.711428       33.570876      71.038560
min      19.000000    6899.000000     0.792581        0.000000       0.859107
25%      20.000000   21862.000000   108.797747       21.286001     106.700286
50%      22.000000   57289.000000   150.267850       31.219121     142.951332
75%      23.000000   89034.000000   199.668538       46.852017     193.174993
max      24.000000  553150.000000   484.154182      280.548322     422.621258

       ...  Violent_Rate  cumulative_eligibility     elig_0_5    elig_6_11  \
count  ...   1198.000000             1198.000000  1198.000000  1198.000000
mean   ...    142.562656                4.569277     1.024930     1.140381
std    ...     59.694936                1.510585     0.282638     0.475278
min    ...      1.004419                1.828912     0.482043     0.472919
25%    ...    105.855199                3.526207     0.787500     0.793958
50%    ...    135.257067                4.244591     0.990642     1.043961
75%    ...    171.176892                5.438220     1.253406     1.363198
max    ...    384.145845                8.991782     1.731209     3.113123

        elig_12_18  trend_cohort  Childhood_Avg_Unemployment  \
count  1198.000000   1198.000000                 1198.000000
mean      2.403966      1.502504                    5.906217
std       1.020116      1.117751                    1.292567
min       0.565799      0.000000                    3.242105
25%       1.645272      1.000000                    4.880263
50%       2.100876      2.000000                    5.810526
75%       3.059532      2.750000                    6.721053
max       5.257803      3.000000                   10.342105

       economically_motivated_crimes  childhood_avg_income  log(income)
count                    1198.000000           1198.000000  1198.000000
mean                      179.394030          12896.260434     9.453259
std                        83.906035           1985.846770     0.150226
min                         0.859107           9177.000000     9.124456
25%                       122.377422          11257.000000     9.328745
50%                       166.161110          12557.000000     9.438034
75%                       229.172412          14220.000000     9.562405
max                       550.145937          18554.000000     9.828441

[8 rows x 21 columns]

**Reasoning**:
Before merging, I need to standardize column names in `df_external` to match `df_children` for key identifiers and drop redundant columns to avoid confusion. Specifically, `fips` should be renamed to `STATEFIP`, `year` to `YEAR`, and `brthyr` to `birth_year`. Additionally, the redundant `Age` column (with an uppercase 'A') should be dropped as it duplicates `age`.

In [ ]:
df_external.rename(columns={'fips': 'STATEFIP', 'year': 'YEAR', 'brthyr': 'birth_year'}, inplace=True)

# Drop the redundant 'Age' column, keeping the lowercase 'age'
if 'Age' in df_external.columns and 'age' in df_external.columns:
    if df_external['age'].equals(df_external['Age']):
        df_external.drop(columns=['Age'], inplace=True)
        print("Dropped redundant 'Age' column. Kept 'age'.")
    else:
        print("WARNING: 'age' and 'Age' columns are different. Keeping both for now.")

print("Columns after renaming and dropping redundant column:")
print(df_external.columns.tolist())

print("\nFirst 5 rows after renaming:")
print(df_external.head())

Dropped redundant 'Age' column. Kept 'age'.
Columns after renaming and dropping redundant column:
['STATEFIP', 'YEAR', 'age', 'crime_count', 'birth_year', 'State', 'Population', 'Drug_Rate', 'Financial_Rate', 'Property_Rate', 'PublicOrder_Rate', 'Violent_Rate', 'cumulative_eligibility', 'elig_0_5', 'elig_6_11', 'elig_12_18', 'trend_cohort', 'Childhood_Avg_Unemployment', 'economically_motivated_crimes', 'state_abb', 'childhood_avg_income', 'log(income)']

First 5 rows after renaming:
   STATEFIP  YEAR  age  crime_count  birth_year State  Population   Drug_Rate  \
0         1  2000   19         1594        1981    AL       67769  142.395491
1         1  2001   19         1741        1982    AL       65031  141.009672
2         1  2001   20         1686        1981    AL       68511  133.263272
3         1  2002   19         1758        1983    AL       64169  154.124266
4         1  2002   20         1655        1982    AL       65515  152.636801

   Financial_Rate  Property_Rate  ...  cumulative_eligibility  elig_0_5  \
0       57.400877     181.498915  ...                3.228658  1.000340
1       66.122311     202.980117  ...                3.559218  0.963729
2       87.285253     159.244501  ...                3.228658  1.000340
3       55.946018     215.212953  ...                3.929335  0.927237
4       69.449744     183.927345  ...                3.559218  0.963729

   elig_6_11  elig_12_18  trend_cohort  Childhood_Avg_Unemployment  \
0   0.858396    1.369921             0                    7.957895
1   0.939953    1.655536             1                    7.642105
2   0.858396    1.369921             0                    7.957895
3   0.999889    2.002209             2                    7.168421
4   0.939953    1.655536             1                    7.642105

   economically_motivated_crimes  state_abb  childhood_avg_income log(income)
0                     235.210790         AL                 10537    9.262648
1                     267.718473         AL                 10732    9.280985
2                     246.091868         AL                 10537    9.262648
3                     273.964064         AL                 10937    9.299907
4                     252.613905         AL                 10732    9.280985

[5 rows x 22 columns]

In [ ]:
import numpy as np

# Step 1: Select ONLY the columns we need from df_external
# These are the eligibility variables and childhood economic controls
# They are constant within a STATEFIP x birth_year cell, so 'first' is correct
elig_crosswalk_cols = [
    'STATEFIP', 'birth_year',
    'cumulative_eligibility', 'elig_0_5', 'elig_6_11', 'elig_12_18',
    'Childhood_Avg_Unemployment', 'childhood_avg_income'
]

# Verify all columns exist in df_external
missing = [c for c in elig_crosswalk_cols if c not in df_external.columns]
if missing:
    print(f"WARNING: Missing columns in df_external: {missing}")
    print(f"Available columns: {df_external.columns.tolist()}")
else:
    print("SUCCESS: All required columns found in df_external.")

# Step 2: Deduplicate to one row per STATEFIP x birth_year
elig_crosswalk = df_external[elig_crosswalk_cols].drop_duplicates(subset=['STATEFIP', 'birth_year'])

print(f"\nEligibility crosswalk shape: {elig_crosswalk.shape}")
print(f"Expected: ~{df_external['STATEFIP'].nunique()} states x {df_external['birth_year'].nunique()} cohorts = {df_external['STATEFIP'].nunique() * df_external['birth_year'].nunique()} rows")
print(f"\nCrosswalk sample:")
print(elig_crosswalk.head(10))

# Step 3: Create log_childhood_income in the crosswalk
elig_crosswalk['log_childhood_income'] = np.log(elig_crosswalk['childhood_avg_income'].clip(lower=1))
print(f"\nlog_childhood_income range: {elig_crosswalk['log_childhood_income'].min():.2f} to {elig_crosswalk['log_childhood_income'].max():.2f}")

# Step 4: Ensure merge keys are the same dtype in both DataFrames
df_children['STATEFIP'] = df_children['STATEFIP'].astype(int)
df_children['birth_year'] = df_children['birth_year'].astype(int)
elig_crosswalk['STATEFIP'] = elig_crosswalk['STATEFIP'].astype(int)
elig_crosswalk['birth_year'] = elig_crosswalk['birth_year'].astype(int)

# Step 5: Perform the merge - should be 1:many (one crosswalk row to many children)
pre_merge_rows = len(df_children)

df_merged = pd.merge(
    df_children,
    elig_crosswalk,
    on=['STATEFIP', 'birth_year'],
    how='left'
)

post_merge_rows = len(df_merged)

# Step 6: CRITICAL DIAGNOSTIC - verify no row inflation
print(f"\n{'='*60}")
print(f"MERGE DIAGNOSTICS")
print(f"{'='*60}")
print(f"df_children rows before merge:  {pre_merge_rows:,}")
print(f"df_merged rows after merge:     {post_merge_rows:,}")
print(f"Row inflation factor:           {post_merge_rows / pre_merge_rows:.4f}")

if post_merge_rows == pre_merge_rows:
    print("✓ PASS: No row inflation. Merge is correct.")
else:
    print("✗ FAIL: Row count changed! Investigate duplicate keys in crosswalk.")
    # Debug: check for duplicates
    dupes = elig_crosswalk[elig_crosswalk.duplicated(subset=['STATEFIP', 'birth_year'], keep=False)]
    print(f"  Duplicate rows in crosswalk: {len(dupes)}")

# Step 7: Check merge success rate
n_matched = df_merged['cumulative_eligibility'].notna().sum()
n_total = len(df_merged)
print(f"\nMerge success: {n_matched:,} / {n_total:,} ({n_matched/n_total:.1%}) children matched to eligibility data")

# Check which birth_year x STATEFIP combinations failed to match
if n_matched < n_total:
    unmatched = df_merged[df_merged['cumulative_eligibility'].isna()]
    print(f"\nUnmatched observations by birth_year:")
    print(unmatched['birth_year'].value_counts().sort_index())
    print(f"\nUnmatched observations by STATEFIP (top 10):")
    print(unmatched['STATEFIP'].value_counts().head(10))

# Step 8: Rename age column for clarity if needed
if 'age' in df_merged.columns:
    df_merged.rename(columns={'age': 'age_child'}, inplace=True)
elif 'AGE' in df_merged.columns:
    df_merged.rename(columns={'AGE': 'age_child'}, inplace=True)

# Step 9: Final shape and column check
print(f"\nFinal df_merged shape: {df_merged.shape}")
print(f"\nKey columns present:")
for col in ['STATEFIP', 'birth_year', 'age_child', 'YEAR', 'HHINCOME',
            'cumulative_eligibility', 'elig_0_5', 'elig_6_11', 'elig_12_18',
            'Childhood_Avg_Unemployment', 'log_childhood_income',
            'ASECWT', 'SEX', 'RACE', 'HISPAN',
            'OFFPOV', 'FOODSTMP', 'HIMCAIDLY', 'HCOVPRIV']:
    if col in df_merged.columns:
        non_null = df_merged[col].notna().sum()
        print(f"  ✓ {col}: {non_null:,} non-null ({non_null/len(df_merged):.1%})")
    else:
        print(f"  ✗ {col}: MISSING")

SUCCESS: All required columns found in df_external.

Eligibility crosswalk shape: (200, 8)
Expected: ~50 states x 4 cohorts = 200 rows

Crosswalk sample:
    STATEFIP  birth_year  cumulative_eligibility  elig_0_5  elig_6_11  \
0          1        1981                3.228658  1.000340   0.858396
1          1        1982                3.559218  0.963729   0.939953
3          1        1983                3.929335  0.927237   0.999889
6          1        1984                4.904218  0.901487   1.445018
24         2        1981                4.208677  1.504931   1.219095
25         2        1982                4.484188  1.489477   1.277632
27         2        1983                4.839657  1.480072   1.310137
30         2        1984                5.606240  1.392732   1.723248
48         4        1981                3.278958  0.712344   1.161997
49         4        1982                3.722614  0.821584   1.258922

    elig_12_18  Childhood_Avg_Unemployment  childhood_avg_income
0     1.369921                    7.957895                 10537
1     1.655536                    7.642105                 10732
3     2.002209                    7.168421                 10937
6     2.557714                    6.752632                 11137
24    1.484651                    8.442105                 15957
25    1.717079                    8.284211                 15926
27    2.049448                    8.100000                 15862
30    2.490260                    7.963158                 15849
48    1.404617                    6.163158                 11735
49    1.642109                    6.047368                 11882

log_childhood_income range: 9.12 to 9.83

============================================================
MERGE DIAGNOSTICS
============================================================
df_children rows before merge:  177,194
df_merged rows after merge:     177,194
Row inflation factor:           1.0000
✓ PASS: No row inflation. Merge is correct.

Merge success: 170,209 / 177,194 (96.1%) children matched to eligibility data

Unmatched observations by birth_year:
birth_year
1981    1604
1982    1665
1983    1905
1984    1811
Name: count, dtype: int64

Unmatched observations by STATEFIP (top 10):
STATEFIP
12    6985
Name: count, dtype: int64

Final df_merged shape: (177194, 59)

Key columns present:
  ✓ STATEFIP: 177,194 non-null (100.0%)
  ✓ birth_year: 177,194 non-null (100.0%)
  ✓ age_child: 177,194 non-null (100.0%)
  ✓ YEAR: 177,194 non-null (100.0%)
  ✓ HHINCOME: 177,194 non-null (100.0%)
  ✓ cumulative_eligibility: 170,209 non-null (96.1%)
  ✓ elig_0_5: 170,209 non-null (96.1%)
  ✓ elig_6_11: 170,209 non-null (96.1%)
  ✓ elig_12_18: 170,209 non-null (96.1%)
  ✓ Childhood_Avg_Unemployment: 170,209 non-null (96.1%)
  ✓ log_childhood_income: 170,209 non-null (96.1%)
  ✓ ASECWT: 177,194 non-null (100.0%)
  ✓ SEX: 177,194 non-null (100.0%)
  ✓ RACE: 177,194 non-null (100.0%)
  ✓ HISPAN: 177,194 non-null (100.0%)
  ✓ OFFPOV: 177,194 non-null (100.0%)
  ✓ FOODSTMP: 177,194 non-null (100.0%)
  ✓ HIMCAIDLY: 177,194 non-null (100.0%)
  ✓ HCOVPRIV: 120,667 non-null (68.1%)

**Reasoning**:
Now that both `df_children` and `df_external` are prepared with consistent column names, the next step is to merge them based on common identifying columns (`STATEFIP`, `YEAR`, `age`, `birth_year`) to combine the household and child data with the external Medicaid and economic variables. A left merge is appropriate here to ensure all records from `df_children` are retained, and matching data from `df_external` is added.

In [ ]:
import pandas as pd
import numpy as np

# --- Step 1: Load and process annual eligibility data from .dta file ---
file_path_annual_eligibility = '/content/drive/MyDrive/Colab Notebooks/Thesis/Data/BKL Calculator/Datafortheweb/BKL.Medicaid.Calculator/medicaidcalc_cpsinst_bkl.dta'
df_annual_eligibility = pd.read_stata(file_path_annual_eligibility)

print("Loaded df_annual_eligibility from .dta file.")

# --- Step 2: Calculate cumulative eligibility from annual data ---
# Select the columns fips, brthyr, age, and sim_eligfpl
columns_to_select = ['fips', 'brthyr', 'age', 'sim_eligfpl']
df_cumulative_annual_eligibility = df_annual_eligibility[columns_to_select].copy()

# Drop any rows with NaN values in selected columns
df_cumulative_annual_eligibility.dropna(subset=columns_to_select, inplace=True)

# Convert key identifier columns to integer data types
df_cumulative_annual_eligibility['fips'] = df_cumulative_annual_eligibility['fips'].astype(int)
df_cumulative_annual_eligibility['brthyr'] = df_cumulative_annual_eligibility['brthyr'].astype(int)
df_cumulative_annual_eligibility['age'] = df_cumulative_annual_eligibility['age'].astype(int)

# Sort the DataFrame by fips, brthyr, and age
df_cumulative_annual_eligibility.sort_values(by=['fips', 'brthyr', 'age'], inplace=True)

# Remove duplicate rows based on the grouping keys
df_cumulative_annual_eligibility.drop_duplicates(subset=['fips', 'brthyr', 'age'], inplace=True)

# Group by fips and brthyr, then calculate the cumulative sum of sim_eligfpl
df_cumulative_annual_eligibility['cumulative_eligibility_to_date'] = \
    df_cumulative_annual_eligibility.groupby(['fips', 'brthyr'])['sim_eligfpl'].cumsum()

# Rename columns to match df_merged
df_cumulative_annual_eligibility.rename(columns={
    'fips': 'STATEFIP',
    'brthyr': 'birth_year',
    'age': 'age_child'
}, inplace=True)

print("Calculated df_cumulative_annual_eligibility.")
print(df_cumulative_annual_eligibility.head())

# --- Step 3: Merge new cumulative eligibility into main DataFrame ---
# Store the number of rows before merge for verification
pre_merge_rows = len(df_merged)

# Drop the existing 'cumulative_eligibility_at_age' column from df_merged if it exists
if 'cumulative_eligibility_at_age' in df_merged.columns:
    df_merged.drop(columns=['cumulative_eligibility_at_age'], inplace=True)
    print("Dropped existing 'cumulative_eligibility_at_age' from df_merged.")

# Perform a left merge of df_merged with the new cumulative annual eligibility
# Select only the necessary columns from df_cumulative_annual_eligibility for merging
subset_df_cumulative_annual_eligibility = df_cumulative_annual_eligibility[[
    'STATEFIP', 'birth_year', 'age_child', 'cumulative_eligibility_to_date'
]]
df_merged = pd.merge(
    df_merged,
    subset_df_cumulative_annual_eligibility,
    on=['STATEFIP', 'birth_year', 'age_child'],
    how='left'
)

# Rename the newly merged column 'cumulative_eligibility_to_date' in df_merged
df_merged.rename(columns={'cumulative_eligibility_to_date': 'cumulative_eligibility_at_age'}, inplace=True)

# Store the number of rows in df_merged after the merge
post_merge_rows = len(df_merged)

# Compare pre_merge_rows and post_merge_rows to verify no row inflation
print(f"\nRows before merge: {pre_merge_rows:,}")
print(f"Rows after merge: {post_merge_rows:,}")
if pre_merge_rows == post_merge_rows:
    print("SUCCESS: No row inflation or deflation occurred during the merge.")
else:
    print("WARNING: Row count changed! Investigate possible issues.")

# Calculate and print the count of non-null values for the 'cumulative_eligibility_at_age' column
n_matched_elig_new = df_merged['cumulative_eligibility_at_age'].notna().sum()
n_total_elig_new = len(df_merged)
print(f"\nNumber of non-null 'cumulative_eligibility_at_age' values: {n_matched_elig_new:,} out of {n_total_elig_new:,} ({n_matched_elig_new/n_total_elig_new:.1%})\n")

print("Updated 'cumulative_eligibility_at_age' in df_merged with non-averaged annual data.")

Loaded df_annual_eligibility from .dta file.
Calculated df_cumulative_annual_eligibility.
     STATEFIP  birth_year  age_child  sim_eligfpl  \
0           1        1981          0     0.177416
12          1        1981          1     0.181689
36          1        1981          2     0.181310
72          1        1981          3     0.176968
120         1        1981          4     0.138957

     cumulative_eligibility_to_date
0                          0.177416
12                         0.359105
36                         0.540415
72                         0.717383
120                        0.856340
Dropped existing 'cumulative_eligibility_at_age' from df_merged.

Rows before merge: 177,194
Rows after merge: 177,194
SUCCESS: No row inflation or deflation occurred during the merge.

Number of non-null 'cumulative_eligibility_at_age' values: 177,194 out of 177,194 (100.0%)

Updated 'cumulative_eligibility_at_age' in df_merged with non-averaged annual data.

## Final Task

### Subtask:
Summarize the successful re-creation and verification of the `df_cumulative_eligibility` DataFrame, confirming that the new calculation method for cumulative eligibility at age has been implemented and validated.

## Merge Cumulative Eligibility and Create Outcomes

### Subtask:
Merge the calculated cumulative eligibility data into the main DataFrame and create several outcome variables.

**Reasoning**:
The subtask is to merge cumulative eligibility data and create outcome variables. The first step is to prepare the `df_cumulative_eligibility` by selecting relevant columns and dropping any potential duplicates before merging.

In [ ]:
import numpy as np

# 1. Select and deduplicate columns from df_cumulative_eligibility
# Ensure 'age_child' is used for merge key from df_merged, so 'age' from df_cumulative_eligibility needs to be kept as is for now.
merge_elig_df = df_cumulative_eligibility[[
    'STATEFIP', 'birth_year', 'age', 'cumulative_eligibility_at_age'
]].drop_duplicates(subset=['STATEFIP', 'birth_year', 'age'])

# 2. Store the current number of rows in df_merged before performing the merge.
pre_merge_rows_final = len(df_merged)

print(f"Shape of merge_elig_df after deduplication: {merge_elig_df.shape}")
print(f"Rows in df_merged before final merge: {pre_merge_rows_final}")

Shape of merge_elig_df after deduplication: (3876, 4)
Rows in df_merged before final merge: 177194

**Reasoning**:
Perform the left merge of `df_merged` with the prepared `merge_elig_df` using `STATEFIP`, `birth_year`, and `age_child`/`age` as keys. Then, verify the merge by checking for row inflation, the count of non-null values in the new eligibility column, and the monotonic increase of `cumulative_eligibility_at_age` with `age_child`.

In [ ]:
df_merged = pd.merge(
    df_merged,
    merge_elig_df,
    left_on=['STATEFIP', 'birth_year', 'age_child'],
    right_on=['STATEFIP', 'birth_year', 'age'],
    how='left'
)

# Drop the redundant 'age' column from merge_elig_df after merge
df_merged.drop(columns=['age'], inplace=True)

# 4. Print the number of rows in df_merged after the merge and compare
post_merge_rows_final = len(df_merged)
print(f"Rows in df_merged after final merge: {post_merge_rows_final}")
print(f"Row inflation check: {post_merge_rows_final / pre_merge_rows_final:.4f}")
if post_merge_rows_final == pre_merge_rows_final:
    print("SUCCESS: No row inflation occurred during the merge.")
else:
    print("WARNING: Row count changed! Investigate possible issues.")

# 5. Print the number of non-null values in the newly merged column
n_matched_elig = df_merged['cumulative_eligibility_at_age'].notna().sum()
n_total_elig = len(df_merged)
print(f"Number of non-null 'cumulative_eligibility_at_age' values: {n_matched_elig:,} out of {n_total_elig:,} ({n_matched_elig/n_total_elig:.1%})")

# 6. Calculate and print the mean of cumulative_eligibility_at_age grouped by age_child
print("\nMean of cumulative_eligibility_at_age grouped by age_child:")
print(df_merged.groupby('age_child')['cumulative_eligibility_at_age'].mean())

Rows in df_merged after final merge: 177194
Row inflation check: 1.0000
SUCCESS: No row inflation occurred during the merge.
Number of non-null 'cumulative_eligibility_at_age' values: 170,209 out of 177,194 (96.1%)

Mean of cumulative_eligibility_at_age grouped by age_child:
age_child
0     0.180209
1     0.360464
2     0.543605
3     0.726214
4     0.906557
5     1.084797
6     1.280604
7     1.484082
8     1.686202
9     1.883492
10    2.083790
11    2.286556
12    2.635529
13    2.975285
14    3.323315
15    3.690005
16    4.069736
17    4.604644
18    4.969073
Name: cumulative_eligibility_at_age, dtype: float64

**Reasoning**:
Now that the cumulative eligibility data has been successfully merged, the next step is to create the specified outcome variables: `in_poverty`, `on_foodstamps`, `has_medicaid`, `uninsured`, and `log_HHINCOME`. This involves conditional assignments and a logarithmic transformation. Finally, the mean of these new outcome variables will be printed to summarize their distributions.

In [ ]:
import numpy as np

# 7. Create `in_poverty` (OFFPOV == 1)
df_merged['in_poverty'] = (df_merged['OFFPOV'] == 1).astype(int)

# 8. Create `on_foodstamps` (FOODSTMP == 2)
df_merged['on_foodstamps'] = (df_merged['FOODSTMP'] == 2).astype(int)

# 9. Create `has_medicaid` (HIMCAIDLY == 2)
df_merged['has_medicaid'] = (df_merged['HIMCAIDLY'] == 2).astype(int)

# 10. Create `uninsured` (HCOVPRIV == 2 AND HIMCAIDLY != 2)
df_merged['uninsured'] = ((df_merged['HCOVPRIV'] == 2) & (df_merged['HIMCAIDLY'] != 2)).astype(int)

# 11. Replace HHINCOME <= 0 with NaN
df_merged['HHINCOME'] = df_merged['HHINCOME'].replace(0, np.nan)
df_merged.loc[df_merged['HHINCOME'] < 0, 'HHINCOME'] = np.nan

# 12. Create `log_HHINCOME`
df_merged['log_HHINCOME'] = np.log(df_merged['HHINCOME'])

# 13. Print the mean of the new outcome variables
print("\nMean of New Outcome Variables:")
print(df_merged[['in_poverty', 'on_foodstamps', 'has_medicaid', 'uninsured', 'log_HHINCOME']].mean())

print(f"\nFinal df_merged shape: {df_merged.shape}")

Mean of New Outcome Variables:
in_poverty        0.197004
on_foodstamps     0.157246
has_medicaid      0.156597
uninsured         0.479260
log_HHINCOME     10.244665
dtype: float64

Final df_merged shape: (177194, 67)

**Reasoning**:
The first step is to define the various lists of variables required for the regression analysis as per the instructions, including outcome, eligibility, control, and fixed-effect variables.

In [ ]:
fixed_effect_vars.remove('birth_year')
control_vars.append('birth_year')

print("Updated outcome variables:", outcome_vars)
print("Updated eligibility variables:", eligibility_vars)
print("Updated control variables:", control_vars)
print("Updated fixed effect variables:", fixed_effect_vars)

Updated outcome variables: ['in_poverty', 'on_foodstamps', 'has_medicaid', 'uninsured', 'log_HHINCOME']
Updated eligibility variables: ['cumulative_eligibility_at_age', 'elig_0_5', 'elig_6_11', 'elig_12_18']
Updated control variables: ['Childhood_Avg_Unemployment', 'log_childhood_income', 'birth_year']
Updated fixed effect variables: ['STATEFIP', 'age_child', 'SEX', 'RACE', 'HISPAN']

**Reasoning**:
Now that the variable lists have been modified to treat 'birth_year' as a linear control variable, the next step is to re-execute the regression analysis using these updated lists. This involves recreating the `df_reg` and `df_reg_clean` DataFrames to reflect the new variable categories and then running the WLS regressions.

In [ ]:
import statsmodels.formula.api as smf
import statsmodels.regression.linear_model as sm

# 2. Re-create a list regression_cols by combining all unique column names with updated lists
regression_cols = list(set(
    outcome_vars +
    eligibility_vars +
    control_vars +
    fixed_effect_vars +
    ['ASECWT'] # Add ASECWT explicitly
))

# 3. Re-create df_reg by selecting only the regression_cols from df_merged.
df_reg = df_merged[regression_cols].copy()

# 4. Re-create df_reg_clean by dropping rows from df_reg that have NaN values
#    in any of the control_vars or eligibility_vars. Also, ensure ASECWT is not NaN.
columns_to_check_for_nan = control_vars + eligibility_vars + ['ASECWT']
df_reg_clean = df_reg.dropna(subset=columns_to_check_for_nan).copy()

# 5. Convert the columns specified in fixed_effect_vars in df_reg_clean to the 'category' data type.
for col in fixed_effect_vars:
    df_reg_clean[col] = df_reg_clean[col].astype('category')

# 6. Print the total number of rows in df_reg_clean.
print(f"Total number of rows in df_reg_clean (re-calculated): {len(df_reg_clean)}")

# 7. Re-initialize results_list and rerun regressions
results_list = []

# 8. Loop through each outcome in outcome_vars and then through each elig in eligibility_vars:
for outcome in outcome_vars:
    for elig in eligibility_vars:
        # Inside the loops, create a temporary DataFrame data by dropping rows from df_reg_clean
        # where the current outcome variable is NaN.
        data = df_reg_clean.dropna(subset=[outcome]).copy()

        # Construct the regression formula dynamically as a string.
        # Fixed effects are added using 'C()' for categorical treatment.
        # 'birth_year' is now in control_vars and thus not wrapped in C().
        formula = f"{outcome} ~ {elig} + {' + '.join(control_vars)} + {' + '.join([f'C({fe})' for fe in fixed_effect_vars])}"

        try:
            # Run a Weighted Least Squares (WLS) regression
            # Set weights equal to data['ASECWT']. Cluster standard errors by STATEFIP.
            model = smf.wls(formula=formula, data=data, weights=data['ASECWT']).fit(cov_type='cluster', cov_kwds={'groups': data['STATEFIP']})

            # Extract the coefficient, standard error, p-value for the elig variable
            coeff = model.params[elig]
            std_err = model.bse[elig]
            p_value = model.pvalues[elig]
            r_squared = model.rsquared_adj # Using adjusted R-squared for models with many predictors
            n_obs = model.nobs

            # Append a dictionary containing these results to results_list.
            results_list.append({
                'Outcome': outcome,
                'Eligibility': elig,
                'Coefficient': coeff,
                'Std Error': std_err,
                'P-value': p_value,
                'R-squared': r_squared,
                'N': int(n_obs)
            })

        except Exception as e:
            # Inside the except block, print an error message indicating which outcome/eligibility combination failed.
            print(f"Error running regression for Outcome: {outcome}, Eligibility: {elig} - {e}")

# 9. Convert results_list into a pandas DataFrame called results_df.
results_df = pd.DataFrame(results_list)

print("Regression results DataFrame re-created successfully with updated variables.")
print(results_df.head())

Total number of rows in df_reg_clean (re-calculated): 170209
Regression results DataFrame re-created successfully with updated variables.
         Outcome                    Eligibility  Coefficient  Std Error  \
0     in_poverty  cumulative_eligibility_at_age     0.001539   0.002752
1     in_poverty                       elig_0_5    -0.025537   0.019113
2     in_poverty                      elig_6_11     0.007356   0.007560
3     in_poverty                     elig_12_18     0.001524   0.003587
4  on_foodstamps  cumulative_eligibility_at_age     0.005029   0.005612

    P-value  R-squared       N
0  0.576101   0.110468  170209
1  0.181502   0.110475  170209
2  0.330555   0.110471  170209
3  0.671014   0.110466  170209
4  0.370196   0.103841  170209

**Reasoning**:
Now that the regressions have been re-run with the updated variable lists and the results are stored in `results_df`, the next step is to format these results, create a pivot table for better readability, and then display both the detailed and pivoted results.

In [ ]:
import pandas as pd

# 10. Define a function, add_stars(p_value)
def add_stars(p_value):
    if p_value < 0.01:
        return '***'
    elif p_value < 0.05:
        return '**'
    elif p_value < 0.1:
        return '*'
    else:
        return ''

# 11. Create a new column in results_df called 'Formatted Result'
results_df['Formatted Result'] = results_df.apply(
    lambda row: f"{row['Coefficient']:.3f}{add_stars(row['P-value'])} ({row['Std Error']:.3f})",
    axis=1
)

# 12. Create a pivot table called pivot
pivot = results_df.pivot_table(
    index='Outcome',
    columns='Eligibility',
    values='Formatted Result',
    aggfunc='first' # Specify aggfunc to avoid aggregation error on string values
)

# Ensure the columns are ordered as specified
pivot = pivot[['cumulative_eligibility_at_age', 'elig_0_5', 'elig_6_11', 'elig_12_18']]

# 13. Display pivot and results_df
print("\n--- Regression Results Pivot Table ---")
print(pivot)

print("\n--- Detailed Regression Results DataFrame ---")
print(results_df)

--- Regression Results Pivot Table ---
Eligibility   cumulative_eligibility_at_age        elig_0_5         elig_6_11  \
Outcome
has_medicaid                -0.007* (0.004)  -0.007 (0.017)  0.023*** (0.006)
in_poverty                    0.002 (0.003)  -0.026 (0.019)     0.007 (0.008)
log_HHINCOME                 -0.015 (0.014)   0.010 (0.066)    -0.019 (0.023)
on_foodstamps                 0.005 (0.006)  -0.033 (0.024)     0.011 (0.008)
uninsured                 -0.041*** (0.008)   0.011 (0.023)     0.000 (0.009)

Eligibility        elig_12_18
Outcome
has_medicaid   -0.005 (0.004)
in_poverty      0.002 (0.004)
log_HHINCOME    0.001 (0.012)
on_foodstamps   0.008 (0.005)
uninsured       0.004 (0.005)

--- Detailed Regression Results DataFrame ---
          Outcome                    Eligibility  Coefficient  Std Error  \
0      in_poverty  cumulative_eligibility_at_age     0.001539   0.002752
1      in_poverty                       elig_0_5    -0.025537   0.019113
2      in_poverty                      elig_6_11     0.007356   0.007560
3      in_poverty                     elig_12_18     0.001524   0.003587
4   on_foodstamps  cumulative_eligibility_at_age     0.005029   0.005612
5   on_foodstamps                       elig_0_5    -0.033247   0.023641
6   on_foodstamps                      elig_6_11     0.011142   0.007503
7   on_foodstamps                     elig_12_18     0.007760   0.004725
8    has_medicaid  cumulative_eligibility_at_age    -0.007091   0.004006
9    has_medicaid                       elig_0_5    -0.006532   0.017194
10   has_medicaid                      elig_6_11     0.022671   0.006437
11   has_medicaid                     elig_12_18    -0.004949   0.004400
12      uninsured  cumulative_eligibility_at_age    -0.041217   0.008049
13      uninsured                       elig_0_5     0.010544   0.022843
14      uninsured                      elig_6_11     0.000402   0.009119
15      uninsured                     elig_12_18     0.003721   0.005477
16   log_HHINCOME  cumulative_eligibility_at_age    -0.014697   0.013818
17   log_HHINCOME                       elig_0_5     0.010126   0.066220
18   log_HHINCOME                      elig_6_11    -0.018875   0.022754
19   log_HHINCOME                     elig_12_18     0.001195   0.012185

         P-value  R-squared       N   Formatted Result
0   5.761009e-01   0.110468  170209      0.002 (0.003)
1   1.815020e-01   0.110475  170209     -0.026 (0.019)
2   3.305546e-01   0.110471  170209      0.007 (0.008)
3   6.710136e-01   0.110466  170209      0.002 (0.004)
4   3.701963e-01   0.103841  170209      0.005 (0.006)
5   1.596188e-01   0.103820  170209     -0.033 (0.024)
6   1.375326e-01   0.103817  170209      0.011 (0.008)
7   1.004953e-01   0.103823  170209      0.008 (0.005)
8   7.666924e-02   0.096113  170209    -0.007* (0.004)
9   7.040107e-01   0.096032  170209     -0.007 (0.017)
10  4.280613e-04   0.096102  170209   0.023*** (0.006)
11  2.606339e-01   0.096041  170209     -0.005 (0.004)
12  3.040477e-07   0.407626  170209  -0.041*** (0.008)
13  6.443603e-01   0.406155  170209      0.011 (0.023)
14  9.648156e-01   0.406153  170209      0.000 (0.009)
15  4.968534e-01   0.406156  170209      0.004 (0.005)
16  2.875010e-01   0.238350  169280     -0.015 (0.014)
17  8.784679e-01   0.238300  169280      0.010 (0.066)
18  4.068116e-01   0.238307  169280     -0.019 (0.023)
19  9.219075e-01   0.238300  169280      0.001 (0.012)

## Summary:

### Data Analysis Key Findings

*   The `birth_year` variable was successfully moved from the `fixed_effect_vars` list to the `control_vars` list, altering its treatment in the regression model from a categorical fixed effect to a linear control variable.
*   The data cleaning and preparation steps, including the creation of `df_reg_clean`, were re-executed, resulting in a dataset of 170,209 rows for the regression analysis.
*   Weighted Least Squares (WLS) regressions were successfully re-run for all specified outcome and eligibility combinations, incorporating the updated variable definitions. Standard errors were clustered by `STATEFIP`.
*   The regression results were formatted to display coefficients rounded to three decimal places, accompanied by significance stars (*** for p < 0.01, ** for p < 0.05, \* for p < 0.1), and standard errors in parentheses.
*   A pivot table was generated, providing a clear summary of the formatted regression results, categorized by `Outcome` and `Eligibility`.

### Insights or Next Steps

*   Compare the current regression coefficients and significance levels with the previous model (where `birth_year` was a fixed effect) to understand how treating `birth_year` as a linear control impacts the estimated effects of eligibility variables.
*   Consider conducting model diagnostics to evaluate if the linear assumption for `birth_year` is appropriate or if alternative non-linear specifications (e.g., polynomial terms) might better capture its relationship with the outcomes.

In [86]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import warnings
warnings.filterwarnings("ignore")

# Force a CLEAN copy with NO category dtypes
cols_needed = ['mom_employed', 'dad_employed', 'mom_weeks', 'mom_hours',
               'cumulative_eligibility_at_age', 'elig_0_5', 'elig_6_11', 'elig_12_18',
               'Childhood_Avg_Unemployment', 'log_childhood_income', 'birth_year',
               'STATEFIP', 'age_child', 'SEX', 'RACE', 'HISPAN', 'ASECWT']
cols_available = [c for c in cols_needed if c in df_merged.columns]

df_parent = pd.DataFrame()
for col in cols_available:
    df_parent[col] = pd.to_numeric(df_merged[col], errors='coerce')

print(f"df_parent: {df_parent.shape}")
print(f"Dtypes:\n{df_parent.dtypes}")

parent_outcomes = [v for v in ['mom_employed', 'dad_employed', 'mom_weeks', 'mom_hours']
                   if v in df_parent.columns and df_parent[v].notna().sum() > 1000]
eligibility_vars = ['cumulative_eligibility_at_age', 'elig_0_5', 'elig_6_11', 'elig_12_18']

print(f"\nOutcomes: {parent_outcomes}")

results_list = []

for outcome in parent_outcomes:
    for elig in eligibility_vars:
        formula = (f"{outcome} ~ {elig} + Childhood_Avg_Unemployment + log_childhood_income"
                   f" + birth_year + C(STATEFIP) + C(age_child) + C(SEX) + C(RACE) + C(HISPAN)")

        data = df_parent[[outcome, elig, 'Childhood_Avg_Unemployment', 'log_childhood_income',
                          'birth_year', 'STATEFIP', 'age_child', 'SEX', 'RACE', 'HISPAN',
                          'ASECWT']].dropna().copy()
        data = data[data['ASECWT'] > 0].reset_index(drop=True)

        if len(data) < 100:
            continue

        try:
            model = smf.wls(formula=formula, data=data, weights=data['ASECWT'])
            res = model.fit(cov_type='cluster', cov_kwds={'groups': data['STATEFIP']})

            results_list.append({
                'Outcome': outcome, 'Eligibility': elig,
                'Coefficient': res.params[elig], 'Std Error': res.bse[elig],
                'P-value': res.pvalues[elig], 'N': int(res.nobs)
            })
            print(f"  OK: {outcome} ~ {elig}: coef={res.params[elig]:.4f}, p={res.pvalues[elig]:.4f}")
        except Exception as e:
            print(f"  ERROR: {outcome} ~ {elig}: {e}")

# Format
results_df_parent = pd.DataFrame(results_list)

def add_stars(p):
    if pd.isna(p): return ''
    if p < 0.01: return '***'
    if p < 0.05: return '**'
    if p < 0.1: return '*'
    return ''

results_df_parent['Formatted'] = results_df_parent.apply(
    lambda r: f"{r['Coefficient']:.4f}{add_stars(r['P-value'])} ({r['Std Error']:.4f})", axis=1)

pivot = results_df_parent.pivot_table(
    index='Outcome', columns='Eligibility', values='Formatted', aggfunc='first')
col_order = ['cumulative_eligibility_at_age', 'elig_0_5', 'elig_6_11', 'elig_12_18']
pivot = pivot[[c for c in col_order if c in pivot.columns]]

print("\n" + "="*80)
print("PARENTAL LABOR SUPPLY RESULTS")
print("="*80)
print(pivot)

df_parent: (177194, 17)
Dtypes:
mom_employed                     float64
dad_employed                     float64
mom_weeks                        float64
mom_hours                        float64
cumulative_eligibility_at_age    float64
elig_0_5                         float64
elig_6_11                        float64
elig_12_18                       float64
Childhood_Avg_Unemployment       float64
log_childhood_income             float64
birth_year                         int64
STATEFIP                           int64
age_child                          int64
SEX                                int64
RACE                               int64
HISPAN                             int64
ASECWT                           float64
dtype: object

Outcomes: ['mom_employed', 'dad_employed', 'mom_weeks', 'mom_hours']
  OK: mom_employed ~ cumulative_eligibility_at_age: coef=-0.0080, p=0.3531
  OK: mom_employed ~ elig_0_5: coef=-0.0050, p=0.6632
  OK: mom_employed ~ elig_6_11: coef=-0.0037, p=0.3718
  OK: mom_employed ~ elig_12_18: coef=-0.0012, p=0.6126
  OK: dad_employed ~ cumulative_eligibility_at_age: coef=0.0027, p=0.3969
  OK: dad_employed ~ elig_0_5: coef=-0.0131, p=0.3087
  OK: dad_employed ~ elig_6_11: coef=0.0031, p=0.6761
  OK: dad_employed ~ elig_12_18: coef=-0.0028, p=0.5060
  OK: mom_weeks ~ cumulative_eligibility_at_age: coef=-0.8747, p=0.1087
  OK: mom_weeks ~ elig_0_5: coef=-3.7103, p=0.2061
  OK: mom_weeks ~ elig_6_11: coef=-1.5899, p=0.1404
  OK: mom_weeks ~ elig_12_18: coef=0.1446, p=0.7588
  OK: mom_hours ~ cumulative_eligibility_at_age: coef=0.2670, p=0.5937
  OK: mom_hours ~ elig_0_5: coef=-2.7424, p=0.2617
  OK: mom_hours ~ elig_6_11: coef=1.0943, p=0.1752
  OK: mom_hours ~ elig_12_18: coef=0.9763, p=0.0638

================================================================================
PARENTAL LABOR SUPPLY RESULTS
================================================================================
Eligibility  cumulative_eligibility_at_age          elig_0_5  \
Outcome
dad_employed               0.0027 (0.0032)  -0.0131 (0.0129)
mom_employed              -0.0080 (0.0086)  -0.0050 (0.0114)
mom_hours                  0.2670 (0.5006)  -2.7424 (2.4432)
mom_weeks                 -0.8747 (0.5453)  -3.7103 (2.9342)

Eligibility          elig_6_11        elig_12_18
Outcome
dad_employed   0.0031 (0.0074)  -0.0028 (0.0043)
mom_employed  -0.0037 (0.0041)  -0.0012 (0.0023)
mom_hours      1.0943 (0.8072)  0.9763* (0.5267)
mom_weeks     -1.5899 (1.0783)   0.1446 (0.4710)

In [88]:
print("\n" + "="*80)
print("PARENTAL LABOR SUPPLY RESULTS SUMMARY")
print("="*80)
display(pivot)

================================================================================
PARENTAL LABOR SUPPLY RESULTS SUMMARY
================================================================================

Eligibility,cumulative_eligibility_at_age,elig_0_5,elig_6_11,elig_12_18
Outcome,,,,
dad_employed,0.0027 (0.0032),-0.0131 (0.0129),0.0031 (0.0074),-0.0028 (0.0043)
mom_employed,-0.0080 (0.0086),-0.0050 (0.0114),-0.0037 (0.0041),-0.0012 (0.0023)
mom_hours,0.2670 (0.5006),-2.7424 (2.4432),1.0943 (0.8072),0.9763* (0.5267)
mom_weeks,-0.8747 (0.5453),-3.7103 (2.9342),-1.5899 (1.0783),0.1446 (0.4710)